# Generated by Django 2.0.1 on 2018-02-09 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20180208_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
