# Generated by Django 2.0.1 on 2018-02-10 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('accounts', '0003_auto_20180202_1701'),
        ('message', '0006_auto_20180209_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_receiver_set', to='accounts.Profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_sender_set', to='accounts.Profile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_set', to='team.Team')),
            ],
        ),
    ]
