# Generated by Django 2.0.1 on 2018-02-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_auto_20180215_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='is_apply',
            field=models.BooleanField(default=False),
        ),
    ]
