# Generated by Django 2.0.1 on 2018-02-20 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_invite_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='message.Message'),
        ),
    ]
