# Generated by Django 2.0.1 on 2018-02-23 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0011_auto_20180220_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='message',
        ),
    ]
