# Generated by Django 2.0.1 on 2018-02-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20180214_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_end',
            field=models.BooleanField(default=False),
        ),
    ]
