# Generated by Django 2.0.1 on 2018-02-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_project_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member',
            new_name='profile',
        ),
    ]
