# Generated by Django 2.0.1 on 2018-02-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20180222_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='profile',
            new_name='member',
        ),
    ]
