# Generated by Django 2.0.1 on 2018-02-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_team_is_activate'),
        ('team', '0005_auto_20180222_2233'),
    ]

    operations = [
    ]
