# Generated by Django 2.0.1 on 2018-02-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningBoard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='planningcreate',
            name='author',
            field=models.CharField(default='글쓴이가 없습니다.', max_length=20, verbose_name='글쓴이'),
        ),
        migrations.AlterField(
            model_name='planningcreate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='planningcreate',
            name='recruiting_period',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planningcreate',
            name='recruting_number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='planningcreate',
            name='title',
            field=models.CharField(default='제목이 없습니다.', max_length=20, verbose_name='제목'),
        ),
    ]
