# Generated by Django 2.0.1 on 2018-02-04 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningBoard', '0003_auto_20180205_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planningcreate',
            name='user',
        ),
        migrations.AddField(
            model_name='planningcreate',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PlanningBoard.Tag'),
        ),
    ]
