# Generated by Django 2.0.1 on 2018-02-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningBoard', '0004_auto_20180205_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
        migrations.RemoveField(
            model_name='planningcreate',
            name='tag',
        ),
        migrations.AddField(
            model_name='planningcreate',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='PlanningBoard.Tag'),
        ),
    ]
