# Generated by Django 2.0.1 on 2018-02-05 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PlanningBoard', '0005_auto_20180205_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
