# Generated by Django 2.0.1 on 2018-02-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningBoard', '0006_tag_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningcreate',
            name='author',
            field=models.CharField(max_length=20, null=True, verbose_name='글쓴이'),
        ),
        migrations.AlterField(
            model_name='planningcreate',
            name='title',
            field=models.CharField(max_length=20, null=True, verbose_name='제목'),
        ),
    ]
