# Generated by Django 2.0.1 on 2018-02-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningBoard', '0008_auto_20180206_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningcreate',
            name='author',
            field=models.CharField(max_length=20, verbose_name='글쓴이'),
        ),
    ]
