# Generated by Django 2.0.1 on 2018-02-09 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningBoard', '0011_auto_20180207_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag_Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tag_region',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PlanningBoard.Tag_Province'),
        ),
    ]
