# Generated by Django 2.0.1 on 2018-02-11 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PlanningBoard', '0013_auto_20180209_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True, verbose_name='제목')),
                ('recruiting_period', models.DurationField(blank=True, null=True)),
                ('recruting_number', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='planning/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_set', to=settings.AUTH_USER_MODEL)),
                ('language', models.ManyToManyField(to='PlanningBoard.Tag_Language')),
                ('project', models.ManyToManyField(to='PlanningBoard.Tag_Project')),
                ('region', models.ManyToManyField(to='PlanningBoard.Tag_Region')),
            ],
        ),
        migrations.RemoveField(
            model_name='planningcreate',
            name='language',
        ),
        migrations.RemoveField(
            model_name='planningcreate',
            name='project',
        ),
        migrations.RemoveField(
            model_name='planningcreate',
            name='region',
        ),
        migrations.DeleteModel(
            name='PlanningCreate',
        ),
    ]
