# Generated by Django 2.0.1 on 2018-02-12 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('PlanningBoard', '0014_auto_20180211_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag_Sublanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Subproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Subregion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tag_language',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag_project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag_region',
            name='province',
        ),
        migrations.RemoveField(
            model_name='tag_region',
            name='user',
        ),
        migrations.AddField(
            model_name='planning',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
        migrations.AddField(
            model_name='planning',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Tag_Province',
        ),
        migrations.AddField(
            model_name='tag_subregion',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subregions', to='PlanningBoard.Tag_Region'),
        ),
        migrations.AddField(
            model_name='tag_subproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprojects', to='PlanningBoard.Tag_Project'),
        ),
        migrations.AddField(
            model_name='tag_sublanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublanguages', to='PlanningBoard.Tag_Language'),
        ),
    ]
