# Generated by Django 2.0.1 on 2018-02-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningBoard', '0015_auto_20180212_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='region',
            field=models.ManyToManyField(to='PlanningBoard.Tag_Subregion'),
        ),
    ]
