# Generated by Django 2.0.1 on 2018-02-13 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningBoard', '0016_auto_20180212_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planning',
            old_name='region',
            new_name='subregion',
        ),
    ]
