# Generated by Django 2.0.1 on 2018-02-13 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningBoard', '0017_auto_20180213_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='region',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='PlanningBoard.Tag_Region'),
            preserve_default=False,
        ),
    ]
