# Generated by Django 2.0.1 on 2018-02-13 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningBoard', '0018_planning_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_set', to=settings.AUTH_USER_MODEL, verbose_name='글쓴이'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='recruiting_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='recruting_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
