# Generated by Django 2.0.1 on 2018-02-17 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningBoard', '0019_auto_20180213_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planning',
            old_name='recruting_number',
            new_name='recruiting_number',
        ),
    ]
