# Generated by Django 2.0.1 on 2018-02-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningBoard', '0023_comment_created_at'),
        ('PlanningBoard', '0021_auto_20180215_1419'),
    ]

    operations = [
    ]
