# Generated by Django 2.0.1 on 2018-02-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningBoard', '0024_merge_20180218_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planning',
            old_name='recruting_number',
            new_name='recruiting_number',
        ),
    ]
