# Generated by Django 2.0.1 on 2018-02-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningBoard', '0025_auto_20180220_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=100, verbose_name='댓글'),
        ),
    ]
