# Generated by Django 2.0.1 on 2018-02-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningBoard', '0026_auto_20180223_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=100, verbose_name='댓글'),
        ),
    ]
