# Generated by Django 2.0.1 on 2018-02-14 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='제목')),
                ('club_name', models.TextField(default='예시: 피로그래밍', verbose_name='동아리 이름')),
                ('recruiting_period', models.DateTimeField(blank=True, null=True, verbose_name='모집 마감일 #YYYY-MM-DD 형식으로 입력하세요.')),
                ('recruiting_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='모집 인원')),
                ('description', models.TextField(verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정 날짜')),
                ('image', models.ImageField(blank=True, height_field=100, null=True, upload_to='blog/%Y/%m/%d/', verbose_name='동아리 포스터', width_field=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='글쓴이')),
                ('like_set', models.ManyToManyField(related_name='did_like_article_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
