# Generated by Django 2.0.1 on 2018-02-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180217_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='like_club',
            field=models.ManyToManyField(blank=True, null=True, to='ClubBoard.Create_Post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='like_info',
            field=models.ManyToManyField(blank=True, null=True, to='InformationBoard.Info_Article'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='like_planning',
            field=models.ManyToManyField(blank=True, null=True, to='PlanningBoard.Planning'),
        ),
    ]
