# Generated by Django 2.0.1 on 2018-02-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180222_1554'),
        ('accounts', '0005_auto_20180221_1733'),
    ]

    operations = [
    ]
