# Generated by Django 2.0.1 on 2018-02-27 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20180223_1923'),
        ('accounts', '0006_merge_20180223_2115'),
        ('accounts', '0006_merge_20180223_1916'),
    ]

    operations = [
    ]
