# Generated by Django 2.0.1 on 2018-02-14 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_article',
            name='like_set',
            field=models.ManyToManyField(related_name='info_board_article_liked_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
