# Generated by Django 2.0.1 on 2018-02-18 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InformationBoard', '0002_auto_20180214_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info_comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='info_comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='info_article',
            name='due',
        ),
        migrations.RemoveField(
            model_name='info_article',
            name='personnel',
        ),
        migrations.AddField(
            model_name='info_article',
            name='image',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='blog/%Y/%m/%d/', verbose_name='대회정보 포스터', width_field=50),
        ),
        migrations.AddField(
            model_name='info_article',
            name='recruiting_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='모집 인원'),
        ),
        migrations.AddField(
            model_name='info_article',
            name='recruiting_period',
            field=models.DateTimeField(blank=True, null=True, verbose_name='모집 마감일 #YYYY-MM-DD 형식으로 입력하세요.'),
        ),
        migrations.AlterField(
            model_name='info_article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='글쓴이'),
        ),
        migrations.DeleteModel(
            name='Info_Comment',
        ),
    ]
