# Generated by Django 2.0.1 on 2018-02-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationBoard', '0003_auto_20180219_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_article',
            name='url',
            field=models.URLField(blank=True, default='/', null=True),
        ),
    ]
