# Generated by Django 2.0.1 on 2018-02-19 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('InformationBoard', '0004_info_article_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_article',
            name='recruiting_number',
            field=models.CharField(default='10', max_length=30, verbose_name='모집 인원'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info_article',
            name='recruiting_period',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='모집 마감일 #YYYY-MM-DD 형식으로 입력하세요.'),
            preserve_default=False,
        ),
    ]
